:<<! 
[script description]: build a datastore for enhance-knn-sr
[dataset]: data generated by End2End
[base model]: End2End
!
# this line speed up faiss
export OMP_WAIT_POLICY=PASSIVE

PROJECT_PATH=$( cd -- "$( dirname -- "$ BASH_SOURCE[0]}" )" &> /dev/null && pwd )/../..
BASE_MODEL=symbolicregression/weights/model1.pt
DATA_PATH=./data
DATASTORE_SAVE_PATH=$PROJECT_PATH/datastore/symbolicregression/end2end_epoch-30000


CUDA_VISIBLE_DEVICES=0 python $PROJECT_PATH/knnbox-scripts/common_sr/validate.py $DATA_PATH \
--task translation \
--path $BASE_MODEL \
--model-overrides "{'eval_bleu': False, 'required_seq_len_multiple':1, 'load_alignments': False}" \
--dataset-impl mmap \
--valid-subset train \
--skip-invalid-size-inputs-valid-test \
--max-tokens 4096 \
--bpe fastbpe \
--user-dir $PROJECT_PATH/knnbox/models \
--arch robust_knn_mt@transformer_wmt19_de_en \
--knn-mode build_datastore \
--knn-datastore-path  $DATASTORE_SAVE_PATH \
